### PR TITLE
Blog Page Redesign and Console Launch Button

### PR DESCRIPTION
**Pull request by ArthurEmma2**
This pull request addresses two significant aspects. Firstly, it encompasses the redesign of the blog page to enhance user experience and visual appeal, focusing on layout optimization, responsive design, and interactive features. Secondly, the PR resolves the issue raised during the last WG-Akash-Website meeting by introducing a prominent "Launch Console" button, accompanied by a diagonal arrow indicating that the action will open a new tab. These improvements are expected to lead to increased user engagement, higher readership, and improved overall navigation on the website.
this PR solves #192  and #201

Link for review: https://akashtesting.netlify.app/

### CODE REVIEW

**Comment by HoomanHQ** [comment]
IMG_20230825_173443

In blog page(mobile view) at the bottom: this section looks different compared to what's on the landing page, do make it consistent and similar to what's on the landing page..

**Comment by ArthurEmma2** [comment]
> IMG_20230825_173443
> 
> In blog page(mobile view) at the bottom: this section looks different compared to what's on the landing page, do make it consistent and similar to what's on the landing page..

Thanks, I have fixed it you can click on the link for a review

Link: https://akashtesting.netlify.app/

**Comment by HoomanHQ** [comment]
THANK YOU: On the blog page, still the newsletter is not spread over full screen, seems to be coded in a box which is not matching the landing page newsletter: i want you to make it 100% similar to whats on the landing page.

Some in-depth analysis + thoughts as per current PR #232 :

1) deep nesting like this can be avoided using classes or id's:
image

2) inline styles can be avoided (depending on circumstances)
image

3) As CSS files are created separately for every page or component, these type of style tag can be avoided also:
image


**NOTE: THESE ARE NOT MAJOR ISSUES IN CURRENT SITUATION BUT THE RULES SHOULD BE FOLLOWED FROM NEXT TIME, SO WE HAVE A WELL STRUCTURED FRAMEWORK FOR UPCOMING IMPLEMENTATIONS..**

Thank you

**Comment by ArthurEmma2** [comment]
> THANK YOU: On the blog page, still the newsletter is not spread over full screen, seems to be coded in a box which is not matching the landing page newsletter: i want you to make it 100% similar to whats on the landing page.
> 
> **Some in-depth analysis + thoughts as per current PR #232 :**
> 
> 1. deep nesting like this can be avoided using classes or id's:
>    image
> 2. inline styles can be avoided (depending on circumstances)
>    image
> 3. As CSS files are created separately for every page or component, these type of style tag can be avoided also:
>    image
> 
> **NOTE: THESE ARE NOT MAJOR ISSUES IN CURRENT SITUATION BUT THE RULES SHOULD BE FOLLOWED FROM NEXT TIME, SO WE HAVE A WELL STRUCTURED FRAMEWORK FOR UPCOMING IMPLEMENTATIONS..**
> 
> Thank you

**Comment by ArthurEmma2** [comment]
> THANK YOU: On the blog page, still the newsletter is not spread over full screen, seems to be coded in a box which is not matching the landing page newsletter: i want you to make it 100% similar to whats on the landing page.
> 
> **Some in-depth analysis + thoughts as per current PR #232 :**
> 
> 1. deep nesting like this can be avoided using classes or id's:
>    image
> 2. inline styles can be avoided (depending on circumstances)
>    image
> 3. As CSS files are created separately for every page or component, these type of style tag can be avoided also:
>    image
> 
> **NOTE: THESE ARE NOT MAJOR ISSUES IN CURRENT SITUATION BUT THE RULES SHOULD BE FOLLOWED FROM NEXT TIME, SO WE HAVE A WELL STRUCTURED FRAMEWORK FOR UPCOMING IMPLEMENTATIONS..**
> 
> Thank you

I do not see any problem with the newsletter width the newsletter background has the same width across the two pages. I guess you need to refresh your browser and check again. Thanks

**Comment by ArthurEmma2** [comment]
"2.inline styles can be avoided (depending on circumstances)" 

Bootstrap does not have a direct class to control the text-underline-offset, and there is no need for me to create an entire CSS file just for the text-underline-offset.

**Comment by HoomanHQ** [comment]
@ArthurEmma2 
It seems like there's a critical issue that needs to be addressed before merging. The blog page is displaying multiple times without CSS styling during certain interactions. Additionally, upon refreshing the page, the CSS styling is fetched correctly. 

This might be due to some CSS file calling issues. To fix the problem, review the code responsible for loading the CSS and ensure that the appropriate styles are applied consistently.

Screenshot_2023-08-27-00-44-32-907_com android chrome

**Comment by ArthurEmma2** [comment]
> @ArthurEmma2 It seems like there's a critical issue that needs to be addressed before merging. The blog page is displaying multiple times without CSS styling during certain interactions. Additionally, upon refreshing the page, the CSS styling is fetched correctly. 
> 
> This might be due to some CSS file calling issues. To fix the problem, review the code responsible for loading the CSS and ensure that the appropriate styles are applied consistently.
> 
> Screenshot_2023-08-27-00-44-32-907_com android chrome

I'm currently unable to perceive this error on my browser, and I kindly request @aktdenis, @anilmurty, @zachhorn   and @brewsterdrinkwater to provide more information if they're able to replicate the issue. I want to emphasize that the CSS files are in accordance with Hugo's best practices. Additionally, please feel welcome to review the code. If you happen to identify any instance where a CSS file might have been misplaced, your guidance would be greatly appreciated, and I will promptly address the matter. Your assistance is valued.

**Comment by HoomanHQ** [comment]
@ArthurEmma2 check this: https://www.veed.io/view/80606410-6857-4f48-8285-ef76a5f27183?panel=share to

**Comment by ArthurEmma2** [comment]
> @ArthurEmma2 check this: https://www.veed.io/view/80606410-6857-4f48-8285-ef76a5f27183?panel=share

I am patiently awaiting confirmation from others to determine if they can reproduce these errors. I am not observing these errors myself. It is possible that your network is failing to load the CSS files. It's also possible that this might not even be an error if you have a clear understanding of how web browsers function.

In a web browser, HTML content loads before CSS styles. This implies that the browser initially requests and renders the HTML structure of a webpage before applying any CSS styles to it.

Here's the typical order of loading and rendering:

HTML Loading: When you input a URL or click a link, the browser requests the HTML content from the web server. Subsequently, it commences parsing and rendering the HTML structure. It constructs the Document Object Model (DOM), which depicts the hierarchical arrangement of elements on the webpage.

CSS Loading: As the browser comes across <link> or <style> elements in the HTML, it retrieves the linked CSS files or processes the embedded CSS enclosed within the <style> tags. However, the browser persists in parsing and constructing the DOM even if the CSS hasn't fully loaded yet.

Application of CSS Styles: As soon as the CSS is loaded and parsed, the browser commences applying the styles to the corresponding HTML elements. This process is termed rendering. It involves computing the visual attributes of each element, such as positioning, colors, fonts, etc., based on the specified CSS rules.

Webpage Rendering: By integrating the information from the HTML structure and the applied CSS styles, the browser displays the webpage on the screen, generating the visual representation that users perceive and engage with.

**Comment by yhaw-12** [comment]
> > @ArthurEmma2 It seems like there's a critical issue that needs to be addressed before merging. The blog page is displaying multiple times without CSS styling during certain interactions. Additionally, upon refreshing the page, the CSS styling is fetched correctly.
> > This might be due to some CSS file calling issues. To fix the problem, review the code responsible for loading the CSS and ensure that the appropriate styles are applied consistently.
> > Screenshot_2023-08-27-00-44-32-907_com android chrome
> 
> I'm currently unable to perceive this error on my browser, and I kindly request @aktdenis and @brewsterdrinkwater to provide more information if they're able to replicate the issue. I want to emphasize that the CSS files are in accordance with Hugo's best practices. Additionally, please feel welcome to review the code. If you happen to identify any instance where a CSS file might have been misplaced, your guidance would be greatly appreciated, and I will promptly address the matter. Your assistance is valued.



> @ArthurEmma2 It seems like there's a critical issue that needs to be addressed before merging. The blog page is displaying multiple times without CSS styling during certain interactions. Additionally, upon refreshing the page, the CSS styling is fetched correctly.
> 
> This might be due to some CSS file calling issues. To fix the problem, review the code responsible for loading the CSS and ensure that the appropriate styles are applied consistently.
> 
> Screenshot_2023-08-27-00-44-32-907_com android chrome

The process of loading and rendering in web browsers follows a defined sequence. When a user requests a webpage, the browser first fetches and parses the HTML content, constructing the Document Object Model (DOM). Subsequently, it fetches and processes CSS files, applying styles to the DOM elements. The browser then renders the final webpage, combining HTML structure and CSS styles to deliver the visual experience we interact with.


I can't seem to reproduce the error suggested above.  it might be network issues

**Comment by HoomanHQ** [comment]
Maybe a problem on my side: rest all seems fine to me.. 

cc @brewsterdrinkwater @aktdenis 

Thanks @ArthurEmma2

**Comment by ArthurEmma2** [comment]
> Subject: Issue with 'Share This Article' on Blog Page
> 
> Hi @ArthurEmma2 ,
> 
> I hope you're doing well. I wanted to let you know that everything else is in order, and the PR is all set for merging.
> 
> However, we've identified a minor issue with the 'Share this article' feature on the blog page. When clicking on the share button, it directs users to Twitter but only pastes a portion of the link (e.g., /blog/introducing-ip-leases-on-akash-network/) instead of the entire link.
> 
> It would be greatly appreciated if you could address this small matter. Once this issue is resolved, we'll be able to move forward with the PR merge.
> The 
> Thank you for your attention to this matter.

> Subject: Issue with 'Share This Article' on Blog Page
> 
> Hi @ArthurEmma2 ,
> 
> I hope you're doing well. I wanted to let you know that everything else is in order, and the PR is all set for merging.
> 
> However, we've identified a minor issue with the 'Share this article' feature on the blog page. When clicking on the share button, it directs users to Twitter but only pastes a portion of the link (e.g., /blog/introducing-ip-leases-on-akash-network/) instead of the entire link.
> 
> It would be greatly appreciated if you could address this small matter. Once this issue is resolved, we'll be able to move forward with the PR merge.
> 
> Thank you for your attention to this matter.

It's not functional. I want it to go live and see if the code can retrieve the main akash.network URL along with the blog title. If it fails, I will fix it in my next PR, Literally this doesn't introduce any errors in the code. I would like to observe how it will behave when it finally deployed

**Comment by HoomanHQ** [comment]
@ArthurEmma2 : great: fine👍

cc @brewsterdrinkwater @aktdenis @anilmurty : PR is ready to be merged. 
Everything is clear. 

Thank you

**Comment by aktdenis** [comment]
> 

@ArthurEmma2 I'm still seeing this issue. Can you unify appearance of this section on blog and homepage. ty!

**Comment by aktdenis** [comment]
@ArthurEmma2 
linkedin and facebook icons missing in "share article" 
can you add tags in the detail page of blog?

**Comment by aktdenis** [comment]
@ArthurEmma2 
can you have a look at the spacing for the featured blog post. 
also, a quick look at the font sizing would be helpful to polish this thing. (tag tiles are bit off, date & time to read 500 weight) you can have a detailed view @ provided figma link.

**Comment by ArthurEmma2** [comment]
> @ArthurEmma2 linkedin and facebook icons missing in "share article" can you add tags in the detail page of blog?




> @ArthurEmma2 linkedin and facebook icons missing in "share article" can you add tags in the detail page of blog?

@aktdenis can you help me with the social svgs ?

**Comment by ArthurEmma2** [comment]
> > 
> 
> @ArthurEmma2 I'm still seeing this issue. Can you unify appearance of this section on blog and homepage. ty!

**Comment by ArthurEmma2** [comment]
@aktdenis,  new update has been deployed. Please check it out. Remember to refresh the page when you navigate to the blog page to fetch the latest updates.

**Review by anilmurty — APPROVED** [review]

**Comment by brewsterdrinkwater** [comment]
@anilmurty mentioned that the build is failing. 

@HoomanHQ and @ArthurEmma2. Can you look into this?

**Comment by HoomanHQ** [comment]
cc @brewsterdrinkwater @ArthurEmma2 : i can see the size of change is too large, about 1+ gb, which is causing timeout error during the deployment process. 

To resolve this issue: there is one line needs to be added, follow steps listed below:

1. Go to this file: https://github.com/akash-network/website/blob/main/.github/workflows/hugo.yml
2. Update the file with this code: 




In above code: in deployment job, i have added one line which will resolve this issue:    timeout-minutes: 15

Thank you

**Comment by Developer-piyush** [comment]
cc @brewsterdrinkwater @anilmurty : i created a quick patch for this problem in this PR #243 : Merging this pr will resolve the deployment error.

Thank you

**Comment by HoomanHQ** [comment]
cc @brewsterdrinkwater @anilmurty : i created a quick patch for this problem in this PR #243  : Merging this pr will resolve the deployment error.

Thank you

**Comment by ArthurEmma2** [comment]
@anilmurty can you share the Build errors ?

> @anilmurty mentioned that the build is failing.
> 
> @HoomanHQ and @ArthurEmma2. Can you look into this?

**Pull request merged**
