### PR TITLE
Gpu testnet website

### PR DESCRIPTION
**Pull request by ArthurEmma2**
update

### CODE REVIEW

**Comment by anilmurty** [comment]
would be great to see a screenshot and/ or screen recording to review

**Comment by ArthurEmma2** [comment]
> would be great to see a screenshot and/ or screen recording to review


https://github.com/akash-network/website/assets/86601468/c8892c4b-9abc-407f-a337-852b9d1ebcde

Hey @anilmurty  I'm yet to receive the link for View GPU Docs  and KYC Guidelines.

**Review by anilmurty — APPROVED** [review]

**Comment by anilmurty** [comment]
@ArthurEmma2 - looks like some assets were missed in the commit?


This is from the build following this PR commit:

https://github.com/akash-network/website/actions/runs/5158830803/jobs/9296809743

Screenshot 2023-06-02 at 5 10 15 PM

**Comment by anilmurty** [comment]
OK, I fugured out what was missing. 
1. The default index page was changed to the testnet index.md - causing the title to be messed up
2. The asset akash.network/gpu-testnet was not included in the PR (#160)  I think - hence the link was broken.
I've updated to the old index.md and pointed the CTA to the https://akashnet.typeform.com/to/x2fwKQFH typeform for now in https://github.com/akash-network/website/pull/162/files

**Comment by anilmurty** [comment]
ref for what I changed to make the temporary fix https://github.com/akash-network/website/pull/162

**Comment by ArthurEmma2** [comment]
Hey @anilmurty will push an update shortly

**Pull request merged**
