### PR TITLE
Get started page: GPU Tile added 

### PR DESCRIPTION
**Pull request by ArthurEmma2**
This PR  introduces an additional tile to the existing content  providing a seamless way for users to initiate the process of accessing high-performance GPUs on the Akash Network.

### CODE REVIEW

**Comment by aktdenis** [comment]
@ArthurEmma2 can you provide a preview with a link? ty!

**Comment by ArthurEmma2** [comment]
> @ArthurEmma2 can you provide a preview with a link? ty!

Not done with this just a quick fix and it will be ready for merge

**Comment by ArthurEmma2** [comment]
@aktdenis check it out: https://akashtesting.netlify.app/get-started/

**Comment by aktdenis** [comment]
@ArthurEmma2  can you have a look at the gpu button in the navbar:
Screenshot 2023-09-22 at 11 50 01
cc @HoomanHQ

**Comment by aktdenis** [comment]
@ArthurEmma2 
there is no need for a breakpoint after performance:
IMG_1164
two lines works fine

**Comment by aktdenis** [comment]
@ArthurEmma2 also button here: 
B16D4E43-6591-470C-9EC9-F8FC4F6DAC1C

**Comment by ArthurEmma2** [comment]
@aktdenis new update pushed and deploy now ready for merge

**Comment by aktdenis** [comment]
@ArthurEmma2 thank you

**Pull request merged**
