### PR TITLE
Update: Page Title, Banner Link, Header, and Paragraph Styling ( 3 groups )

### PR DESCRIPTION
**Pull request by ArthurEmma2**
1. Refactored code to update the page title and banner link. 
2. Applied light color to the header text and paragraph description( 3 groups ) for improved visibility on mobile screens in dark mode.
3. changed the mobile images from PNG to SVG 

https://github.com/akash-network/website/assets/86601468/77a9b982-b91d-450e-8e7e-27f4eb0766e4

https://github.com/akash-network/website/assets/86601468/993005f2-82d9-4e97-bb1e-ea660ae4eaf1

### CODE REVIEW

**Comment by ArthurEmma2** [comment]
Hey @anilmurty can you please check this PR

**Comment by anilmurty** [comment]
Thanks @ArthurEmma2 - I'm going to build your fork locally and very and then merge

**Comment by anilmurty** [comment]
built and tested locally. Looks OK overall, two issues I'd like fixed (cc @aktdenis  as well) :
1. The title overlaps the text below it when resizing the window (happens in the main page as well as the GPU testnet page - see recording below)
2. I think we should open the testnet CTA page in a new tab (but will let @aktdenis decide whether we should just keep as-is)


https://github.com/akash-network/website/assets/19495789/58de1ca9-5a9a-4db3-909b-32f81f3c9d26

**Comment by anilmurty** [comment]
@ArthurEmma2 - discussed with @aktdenis - let's open CTA link (GPU testnet page) in a new tab

**Comment by ArthurEmma2** [comment]
> @ArthurEmma2 - discussed with @aktdenis - let's open CTA link (GPU testnet page) in a new tab

Cool. Will push update shortly

**Comment by ArthurEmma2** [comment]
Hey @anilmurty I have made a commit

**Comment by ArthurEmma2** [comment]
[screen-capture (3).webm](https://github.com/akash-network/website/assets/86601468/8ff10674-ea1d-4cb7-8eb9-b027b52da8d4)

**Review by anilmurty — APPROVED** [review]

**Comment by anilmurty** [comment]
Thanks @ArthurEmma2 - tested your fork locally - the issues are all resolved now. I'm merging and will test deploy shortly.

**Comment by ArthurEmma2** [comment]
Great

**Pull request merged**
