### PR TITLE
blog: community group intros

### PR DESCRIPTION
**Pull request by gosuri**

### CODE REVIEW

**Review by bmenzalji — CHANGES_REQUESTED** [review]
January 16th, 2023 is a holiday.

Steering Committee Monthly Meeting is scheduled for the last thursday of the month. First one is January 26th, 2023 10am pst

**Comment by zachhorn** [comment]
Updated title: "Public Cloud Is a Public Utility"

**Comment by zachhorn** [comment]
Suggested section update.

**Current:**
> Line 73: We're kicking off the first meeting on January 26th, 2023 10am. We'd love your contributions.

**Updated:**
> Our new working model is already underway, and we have already had several successful WG meetings with the Akash Community and ecosystem partners.
> 
> The first Steering Committee meeting is scheduled for January 26th, 2023. In the meantime, browse Akash's [GitHub](https://github.com/akash-network/community) to learn about the various SIGs and WGs that are currently active — and head over to our Discord to join the conversation.

**Review by anilmurty — APPROVED** [review]
Looks great to me. Just one minor typo:

>>creating a technical specifications based on them

**Comment by gosuri** [comment]
> Looks great to me. Just one minor typo:
> 
> > > creating a technical specifications based on them

@anilmurty which line is this on?

**Comment by anilmurty** [comment]
> > Looks great to me. Just one minor typo:
> > > > creating a technical specifications based on them
> 
> @anilmurty which line is this on?

line 27, 28

**Comment by AKTPete** [comment]
"The Akash Network was created approximately two years ago to decentralize cloud infrastructure and put it in the hands of the people. It's now run by a network of globally distributed node operators who secure the Akash blockchain and provide cloud-grade server space for tenant applications."

The first paragraph has two "its" close to each other and what it is referring to is unclear. 

Is "it" referring to the cloud, or cloud infrastructure? Is the second "it" referring to the cloud, cloud infrastructure or the Akash Network?

**Pull request merged**
