### PR TITLE
Deployment Page: Tab Section Changed to Two Tiles

### PR DESCRIPTION
**Pull request by ArthurEmma2**
The deployment page now features a revamped tab section, which has been replaced with two distinct tiles for improved user navigation and functionality

Live link: https://website-theta-eight-58.vercel.app/deploy/

### CODE REVIEW

**Comment by aktdenis** [comment]
thanks! 

@ArthurEmma2 can we get rid off the white outline in the second and third image. also, there is no need for the line(border) below CTA Launch... 

cc @HoomanHQ 

Screenshot 2023-10-11 at 13 04 57

**Comment by aktdenis** [comment]
@ArthurEmma2  could you please have a look at the icon here. seems outlined and not aligned properly. thanks!
Screenshot 2023-10-11 at 13 57 59

**Comment by ArthurEmma2** [comment]
> thanks!
> 
> @ArthurEmma2 can we get rid off the white outline in the second and third image. also, there is no need for the line(border) below CTA Launch...
> 
> cc @HoomanHQ
> 
> Screenshot 2023-10-11 at 13 04 57

the white outline is part of the svg it's not from my side unless you provide me with a different svg

**Comment by aktdenis** [comment]
@ArthurEmma2 ok, could you please remove it anyway. it's not in the figma file anymore, somehow it sneaked in. thanks

**Comment by ArthurEmma2** [comment]
@aktdenis new update pushed and deployed check it out

**Pull request merged**
